### ISSUE TITLE
Question: Why aren't square brackets considered grouping symbols?

### ISSUE THREAD

**Issue by rdbeach** [Khan/KAS#14]
Why can't I do this:

[1+2]+3

The above returns error.

**Comment by alopatin** [comment]
No particular reason; I guess supporting grouping via parentheses only has been sufficient for us. It would be really easy to add, though. You'd just need to copy [this line](https://github.com/Khan/KAS/blob/master/src/parser-generator.js#L167) but replace `(` & `)` with `[` & `]` (and add some tests, of course).

**Comment by rdbeach** [comment]
Ok thanks, I'll give that a try.
